[workspace]
resolver = "2"
members = [
    "codegen",
    "lolraft",
    "tests/*"
]

[workspace.dependencies]
tonic = "0.11"
tonic-build = "0.11"
prost = "0.12"
prost-build = "0.12"
lolraft = { path = "lolraft" }
