[workspace]
members = [
    "lol-core",
    "lol-admin",
    "lol-monitor",

    # internal
    "integration-tests",

    # examples
    "examples/kvs",
    "examples/multi-services",
    "examples/atomic-counter",
]