version: '3'

services:
  dev:
    image: lol-dev:latest
    working_dir: /work
    volumes:
      - ./:/work
      - /var/run/docker.sock:/var/run/docker.sock

  testapp:
    image: lol-testapp:latest
    entrypoint:
      - /bin/sh