version: '3'

services:
  dev:
    image: ghcr.io/akiradeveloper/lol/lol-dev:latest
    working_dir: /work
    volumes:
      - ./:/work
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - raft-network

  testapp:
    image: ghcr.io/akiradeveloper/lol/lol-testapp:latest
    entrypoint:
      - /bin/sh

networks:
  raft-network:
    driver: bridge