version: '3'

services:
  dev:
    build:
      context: . 
      dockerfile: Dockerfile
    working_dir: /work
    volumes:
      - ./:/work
      - rust_target:/rust_target
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CARGO_BUILD_TARGET_DIR: /rust_target

  log0:
    image: gliderlabs/logspout
    container_name: log0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  log:
    image: rust
    depends_on:
      - log0
    command: sh -c "curl log0:80/logs/name:lol-testapp-*"
    
  testapp:
    image: lol-testapp:latest
    build:
      context: .
      dockerfile: tests/testapp/Dockerfile
    volumes:
      - rust_target:/rust_target
    environment:
      CARGO_BUILD_TARGET_DIR: /rust_target
    entrypoint:
      - /bin/sh

volumes:
  rust_target: